# Generated by Django 5.0.3 on 2024-03-07 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employermodule', '0005_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='applicants',
        ),
        migrations.DeleteModel(
            name='JobApplication',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Applicant',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
