# Generated by Django 5.0 on 2024-03-09 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employermodule', '0007_jobapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
