# Generated by Django 5.0.3 on 2024-03-07 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekermodule', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
