# Generated by Django 5.0 on 2024-03-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekermodule', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='job_details',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
